# FastAPI backend for Maru
#
# HOW TO RUN:
#   pip install -r requirements.txt
#   uvicorn main:app --reload
#
#   --reload  → restarts the server automatically when you save this file (dev only)
#   main      → the filename (main.py)
#   app       → the FastAPI instance created below
#
# Once running:
#   API:  http://localhost:8000
#   Docs: http://localhost:8000/docs  ← interactive API explorer, auto-generated by FastAPI

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# Create the FastAPI app.
# This object holds all your routes, middleware, and settings.
app = FastAPI(title="Maru API")

# CORS (Cross-Origin Resource Sharing) lets the Next.js frontend talk to this server.
# origins=["*"] allows requests from any domain — fine for development.
# TODO: In production, replace "*" with your actual frontend URL, e.g.:
#   origins=["https://maru.vercel.app"]
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ─── Health check ────────────────────────────────────────────────────────────
#
# @app.get("/") is a decorator — it tells FastAPI: "when someone sends a GET
# request to the path '/', call the function below and return its result as JSON."
#
# FastAPI automatically converts the returned dict to a JSON response, so
# {"status": "ok"} becomes: HTTP 200  {"status": "ok"}
#
# You can test this right in the browser: http://localhost:8000/
@app.get("/")
def health_check():
    return {"status": "ok"}


# ─── Apply endpoint ───────────────────────────────────────────────────────────

# Pydantic model — defines and validates the expected request body shape.
# If the client sends wrong types or missing fields, FastAPI returns a 422 error automatically.
class ApplyRequest(BaseModel):
    name: str
    email: str


# POST /apply — receives an application from the "Apply Now" button on the frontend.
# The `body` parameter is automatically parsed from the JSON request body.
@app.post("/apply")
def apply(body: ApplyRequest):
    # TODO: Replace this print with real logic — save to a database, send an email, etc.
    print(f"New application: {body.name} <{body.email}>")

    return {
        "message": f"Thanks {body.name}, we'll be in touch at {body.email}!"
    }
